add header component
Reeju2019/eRip pull request #5
Opened 2022-07-25 13:14 UTC by Mihir0000

2022-07-25 13:31 UTC, Reeju2019 requested changes
I am not sure if this code was ready for my review.
Please refactor this code and push the changes.

2022-07-25 13:31 UTC, Reeju2019 commented on src/Components/Header/HeaderCarousel.tsx
> +                                            Easy Fix <br/> Superior Service Quality Parts
Refer to earlier review and change accordingly

2022-07-25 13:31 UTC, Reeju2019 commented on src/Components/Header/HeaderCarousel.tsx
> +import * as React from 'react';
Please change this to `import React from 'react';`

2022-07-25 13:31 UTC, Reeju2019 commented on src/Components/Header/HeaderCarousel.tsx
> +    props
If their is no props then please remove this

2022-07-25 13:56 UTC, Mihir0000 commented on src/Components/Header/HeaderCarousel.tsx
> +    props
done

2022-07-25 13:57 UTC, Mihir0000 commented on src/Components/Header/HeaderCarousel.tsx
> +    props
done

2022-07-25 13:59 UTC, Mihir0000 commented on src/Components/Header/HeaderCarousel.tsx
> +import * as React from 'react';
done

2022-07-25 13:59 UTC, Mihir0000 commented on src/Components/Header/HeaderCarousel.tsx
> +                                            Top Trained Experts <br/> at Your Doorstep
done

2022-07-25 14:00 UTC, Mihir0000 commented on src/Components/Header/HeaderCarousel.tsx
> +                                            Repair & Maintainence <br />
done

2022-07-25 14:00 UTC, Mihir0000 commented on src/Components/Header/HeaderCarousel.tsx
> +interface IHeaderCarouselProps {}
done

2022-07-25 14:00 UTC, Mihir0000 commented on src/Components/Header/HeaderCarousel.tsx
> +                                            Easy Fix <br/> Superior Service Quality Parts
done

2022-07-26 05:16 UTC, Reeju2019 requested changes

2022-07-26 05:16 UTC, Reeju2019 commented on src/Components/Header/Header.css
> +    background: url(../../../public/static/image/carousel-bg-1.png);
I may be wrong but I think the url can also be written like `/static/image/carousel-bg-1.png`

2022-07-26 05:16 UTC, Reeju2019 commented on src/Components/Header/Header.tsx
> +                                <Modal.Body>have to implement</Modal.Body>
Make the data dynamic
`<Modal.Body>{data.modal.body}</Modal.Body>`

2022-07-26 05:16 UTC, Reeju2019 commented on src/Components/Header/Header.tsx
> +                                    <i className="fas fa-search"></i>
It can also be written as
` <i className="fas fa-search"/>`

2022-07-26 05:16 UTC, Reeju2019 commented on src/Components/Header/Header.tsx
> +                                Contact Us
Refer to the other comment and do the required changes

2022-07-26 05:16 UTC, Reeju2019 commented on src/Components/Header/Header.tsx
> +                                Login
Refer to the other comments

2022-07-26 05:16 UTC, Reeju2019 commented on src/Components/Header/Header.tsx
> +                                <i className="fa-regular fa-user"></i>
I have shared the code snippet for this inside another comment

2022-07-26 05:16 UTC, Reeju2019 commented on src/Components/Header/HeaderCarousel.tsx
> +                                            {HeaderData.header_caro_2_1} <br />{' '}
After br `{' '}` is this really needed?

2022-07-26 05:45 UTC, Mihir0000 commented on src/Components/Header/Header.tsx
> +                                    <i className="fas fa-search"></i>
done

2022-07-26 05:45 UTC, Mihir0000 commented on src/Components/Header/Header.tsx
> +                                Login
done

2022-07-26 05:45 UTC, Mihir0000 commented on src/Components/Header/Header.tsx
> +                                <i className="fa-regular fa-user"></i>
done

2022-07-26 13:45 UTC, Mihir0000 commented on src/Components/Header/Header.tsx
> +                                <Modal.Body>have to implement</Modal.Body>
done

2022-07-26 13:45 UTC, Mihir0000 commented on src/Components/Header/Header.tsx
> +                                Contact Us
done

2022-07-26 13:48 UTC, Mihir0000 commented on src/Components/Header/Header.css
> +    background: url(../../../public/static/image/carousel-bg-1.png);
can't fix with `/static/image/carousel-bg-1.png`

2022-07-26 13:58 UTC, merged